### ISSUE TITLE
Fail npm run after success npm install

### ISSUE THREAD

**Issue by arista011** [dazelpro/nodejs-basic-login#1]
how to i can solve this sir?
notification:
Lifecycle scripts included in nodejs-basic-login@1.0.0:
  test
    echo "Error: no test specified" && exit 1

**Comment by dazelpro** [comment]
Hi, you can run it with command `node index.js` or install nodemon and run it with `nodemon`

**Comment by dazelpro** [comment]
I've added some fixes, and now you can run with the command  `npm run start`
